<?php
include(ROOT_PATH . '/app/views/header.php');
?>

<!-- INI Codigo HTML -->
<div class="min-h-full flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
    <div class="max-w-2xl w-full space-y-8">
      <div>
        <img class="mx-auto h-20 w-auto" src="./images/roosterTodo.png" alt="Workflow">
        <h1 class="mt-6 text-center text-4xl font-extrabold text-red-600">Rooster ToDo</h1>
        <!-- <h2 class="mt-6 text-center text-3xl font-extrabold text-gray-900">Listado de tareas</h2> -->
  
      </div>

      <!-- Hecho con Tablas -->

      <div class="w-full overflow-hidden rounded-lg shadow-xs">
        <div class="w-full overflow-x-auto">
            <table class="w-full whitespace-no-wrap">
                <thead class="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase border-b dark:border-gray-700 bg-gray-50 dark:text-gray-400 dark:bg-gray-800">
                    <tr>
                        <td class="px-4 py-3">Título</td>
                        <td class="px-4 py-3">Estado</td>
                        <td class="px-4 py-3">Fecha</td>
                        <td class="px-4 py-3">Editar</td>
                        <td class="px-4 py-3">Acciones</td>
                    </tr>
                </thead>
                <tbody class="bg-white divide-y dark:divide-gray-700 dark:bg-gray-800 text-gray-700 dark:text-gray-400">
                  <!--  <tr class="">
                        <td class="px-4 py-3">
                            <div class="flex items-center text-sm">
                                <div>
                                    <p class="font-semibold">P13fit - Solucionar bug 001</p>
                                    <p class="text-xs text-gray-600 dark:text-gray-400">Solucionar el error con el que la usuaria Sonia no está teniendo acceso a contenido aunque haya pagado</p>
                                </div>
                            </div>
                        </td>
                        <td class="px-4 py-3">
                          <span class="inline-flex px-2 text-xs font-medium leading-5 rounded-full text-lime-300 bg-lime-600 dark:text-white dark:bg-purple-600">Completado</span>
                        </td>
                        <td class="px-4 py-3"><span class="text-sm">3/2/2020</span></td>
                        <td class="px-4 py-3">
                          <a href="#" style="display: inline-block">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-gray-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
                            </svg>
                          </a>
                        </td>
                        <td class="px-4 py-3">
                          <a href="#" style="display: inline-block">
                          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-lime-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                          </svg>
                        </a>
                          <a href="#" style="display: inline-block"><svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-red-700" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
                          </svg></a>
                        </td>
                    </tr>

                    <tr class="">
                      <td class="px-4 py-3">
                          <div class="flex items-center text-sm">
                              <div>
                                  <p class="font-semibold">P13fit - Solucionar bug 001</p>
                                  <p class="text-xs text-gray-600 dark:text-gray-400">Solucionar el error con el que la usuaria Sonia no está teniendo acceso a contenido aunque haya pagado</p>
                              </div>
                          </div>
                      </td>
                      <td class="px-4 py-3">
                        <span class="inline-flex px-2 text-xs font-medium leading-5 rounded-full text-red-700 bg-red-100 dark:text-red-100 dark:bg-red-700">Pendiente</span></td>
                      <td class="px-4 py-3"><span class="text-sm">3/2/2020</span></td>
                      <td class="px-4 py-3">
                        <a href="#" style="display: inline-block">
                          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-gray-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
                          </svg>
                        </a>
                      </td>
                      <td class="px-4 py-3">
                        <a href="#" style="display: inline-block">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-lime-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                        </svg>
                      </a>
                        <a href="#" style="display: inline-block"><svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-red-700" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
                        </svg></a>
                      </td>
                  </tr>

                  <tr class="">
                    <td class="px-4 py-3">
                        <div class="flex items-center text-sm">
                            <div>
                                <p class="font-semibold">P13fit - Solucionar bug 001</p>
                                <p class="text-xs text-gray-600 dark:text-gray-400">Solucionar el error con el que la usuaria Sonia no está teniendo acceso a contenido aunque haya pagado</p>
                            </div>
                        </div>
                    </td>
                    <td class="px-4 py-3">
                      <span class="inline-flex px-2 text-xs font-medium leading-5 rounded-full text-lime-300 bg-lime-600 dark:text-white dark:bg-purple-600">Completado</span>
                    </td>
                    <td class="px-4 py-3"><span class="text-sm">3/2/2020</span></td>
                    <td class="px-4 py-3">
                      <a href="#" style="display: inline-block">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-gray-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
                        </svg>
                      </a>
                    </td>
                    <td class="px-4 py-3">
                      <a href="#" style="display: inline-block">
                      <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-lime-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                      </svg>
                    </a>
                      <a href="#" style="display: inline-block"><svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-red-700" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
                      </svg></a>
                    </td>
                </tr> -->

                <!-- Inicio - Task -->
                <tr class="">
                  <td class="px-4 py-3">
                      <div class="flex items-center text-sm">
                          <div>
                              <p class="font-semibold">P13fit - Solucionar bug 001</p>
                              <p class="text-xs text-gray-600 dark:text-gray-400">Solucionar el error con el que la usuaria Sonia no está teniendo acceso a contenido aunque haya pagado</p>
                          </div>
                      </div>
                  </td>
                  <td class="px-4 py-3">
                    <span class="inline-flex px-2 text-xs font-medium leading-5 rounded-full text-lime-300 bg-lime-600 dark:text-white dark:bg-purple-600">Completado</span>
                  </td>
                  <td class="px-4 py-3"><span class="text-sm">3/2/2020</span></td>
                  <td class="px-4 py-3">
                    <a href="updatetask" style="display: inline-block">
                      <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-gray-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
                      </svg>
                    </a>
                  </td>
                  <td class="px-4 py-3">
                    <a href="updatetask" style="display: inline-block">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-lime-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                  </a>
                    <a href="deletetask" style="display: inline-block"><svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-red-700" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg></a>
                  </td>                  
              </tr>
              <!-- Fin - Task -->
                </tbody>
            </table>
        </div>
    </div>
          

      <div class="w-full space-y-8">
        <button onclick="window.location.href='createtask'" type="submit" class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-red-500 hover:bg-red-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
          <span class="absolute left-0 inset-y-0 flex items-center pl-3">
            <!-- Heroicon name: solid/lock-closed -->
            <svg class="h-5 w-5 text-red-200 group-hover:text-red-400" xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
            </svg>
          </span>
          Tarea Nueva
        </button>
      </div>
      
    </div>
  </div>

<!-- FIN - Codigo HTML -->

<?php
include(ROOT_PATH . '/app/views/footer.php');
?>
